name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate PDF
      run: PREFIX=install/ make install

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: pdf_files
        path: install/
