name: Compile

on:
  workflow_call: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v31

    - name: Compile PDF files
      run: nix-shell --run "PREFIX=install make install"

    - name: Upload PDF files
      uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: install/
