name: Release

on:
  release:
    types: [created, edited]

jobs:
  compile:
    uses: ./.github/workflows/compile.yml

  release:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: pdf

      - name: Archive presentations
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Presentations.zip'
          path: 'Презентации/'

      - name: Archive homeworks
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Homeworks.zip'
          path: 'Домашние задания/'

      - name: Archive projects
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Projects.zip'
          path: 'Проекты/'

      - name: Upload PDFs to GitHub Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: '*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
