name: Release

on:
  release:
    types: [created, edited]

jobs:
  compile:
    uses: ./.github/workflows/compile.yml

  release:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: pdf

      - name: Archive presentations
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Presentations.zip'
          path: 'Презентации/'

      - name: Archive homeworks
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Homeworks.zip'
          path: 'Домашние задания/'

      - name: Upload PDFs to GitHub Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: '*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v3

      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: pdf
          path: install/

      - name: Upload PDFs to Yandex.Disk
        env:
          TOKEN: ${{ secrets.YANDEX_DISK_TOKEN }}
        run: python ci/deploy.py -t ${TOKEN} -d ./install/
