name: Release PDF Files

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3

    - name: Download PDF
      uses: actions/download-artifact@v4
      with:
        name: pdf
        path: install

    - name: Upload PDFs to GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'install/*.pdf'
        token: ${{ secrets.GITHUB_TOKEN }}
