name: Release PDF Files

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  post-pdf:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'release' }}

    steps:
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: pdf_files

      - name: Upload PDFs to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'install/*.pdf'
          token: ${{ secrets.GITHUB_TOKEN }}
