name: Release PDF Files

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  post-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: pdf_files

      - name: Upload PDFs to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'install/*.pdf'
          token: ${{ secrets.GITHUB_TOKEN }}
